class WorkflowFailedError(Exception):
    pass


class TaskFailedError(Exception):
    pass
